platform :ios, '11.0'

use_frameworks!
inhibit_all_warnings!

def utils
    pod 'SwiftGen', '~> 6.1.0'
    pod 'SwiftLint', '~> 0.30.1'
end

def surf_utils
  $SurfUtils = "https://github.com/surfstudio/iOS-Utils.git"
  $Version = '10.0.2'

  pod 'SurfUtils/StringAttributes', :git => $SurfUtils, :tag => $Version
  pod 'SurfUtils/BlurBuilder', :git => $SurfUtils, :tag => $Version
  pod 'SurfUtils/SettingsRouter', :git => $SurfUtils, :tag => $Version
  pod 'SurfUtils/CommonButton', :git => $SurfUtils, :tag => $Version
end


def surf_lib
    # And other Surf pods, like NodeKit
end

def common_pods
    utils
    surf_utils
    surf_lib

    pod 'lottie-ios', '3.1.3'
end

target 'iSee' do
    common_pods
end
